### ISSUE TITLE
Missing Unit Tests

### ISSUE THREAD

**Issue by bsommardahl** [ivanpaulovich/dotnet-new-caju#6]
This is such a great boilerplate in so many ways. But I felt really let down when I didn't find any unit tests anywhere. This project may be able to provide a great starting point for devs in terms of DDD best practices, but it leaves them in the "wild west" as far as unit testing. While I don't doubt the great design that you have single-handedly put together here, it will eventually turn into a big ball of mud once an undisciplined team has it for a couple of months. 

What I hoped to find was a suite of tests that not only prove and document the inner workings, but also unit tests around the sample structures. This would complete the great example you have here and set dev teams up for success.

**Comment by bsommardahl** [comment]
FWIW, I think this boilerplate has enough promise that I would be willing to help you get unit tests applied here. I might even have some devs on my team who would be willing to help as well.

**Comment by ivanpaulovich** [comment]
Hi @bsommardahl, thank you for the feedback! I agree that the `Caju templatea` do not provide Unit Tests by any flags, but you can workaround that by checking the original code for each architecture style:

* `clean architecture` https://github.com/ivanpaulovich/clean-architecture-manga/tree/master/manga/test.
* `hexagonal architecture` https://github.com/ivanpaulovich/hexagonal-architecture-acerola/tree/master/test.
* `event sourcing` https://github.com/ivanpaulovich/event-sourcing-castanha/tree/master/source/Tests.

I hope that info help you guide the developers using this tool :)

**Comment by bsommardahl** [comment]
YES, this is what was missing. Thank you so much. 

So, the next thing I think you should consider is to provide devs with a "way forward" with your sample structures. Perhaps you (we) could build in some unit tests to show best practices for those things?

**Comment by ivanpaulovich** [comment]
I am happy that you found it useful. I suggest for developers to check the Unit Tests on the original repositories just to see the possibilities of testing the use cases and components in isolation.
In the future I will create content explaining my approach on designing a clean architecture and how I implement the use cases guided by tests.. plans for the future!
