### ISSUE TITLE
Minor inconsistencies between Domain in Clean vs Domain in Hex

### ISSUE THREAD

**Issue by IlSocio** [ivanpaulovich/dotnet-new-caju#7]
Hi, 
first of all, thanks for this awesome piece of work :)
I just generated two .net back-ends using two different architectures: Clean and Hex.

My expectation was that I wouldn't find any difference in the Domain layer, because the Domain should be totally unaware of the different architecture style, am I wrong?

And, in case that the Domain layer should totally match, the one in the Clean architecture seems to provide a slightly better implementation, doesn't it?
(prefer composition over inheritance / sealed classes / private setters)

Another question is related to AutoMapper...
In the Hex architecture, there is AutoMapper to map domain object to responses (implemented in the Infrastructure layer)
While, in the Clean architecture, there exists some manual assignation to map domain object to responses (implemented in the Application layer)
` public AccountOutput(Account account) `

Would it be convenient to leverage AutoMapper in the Clean Architecture too? 
In this case, I suppose we should inject a kind of IAccountMappingService in the Application layer which will take care of mapping the Account to AccountOutput and will be implemented in the Infrastructure using Automapper, or there exists a better solution?

Thanks, 
Marco.

**Comment by ivanpaulovich** [comment]
Hi @IlSocio! Thank you :)

When I started the templates development for the three different architecture styles the domain was pretty much the same. Later I had to evolve them independently and the domain become different.

Yes, the Clean Architecture is the template that I had focused my support. So it has better implementation.

Essentially on the Clean Architecture template there are Presenter objects which do mapping between the application output to the the response output. In my experience I prefer to not use AutoMapper anymore.

I suggest you to take a look on the working in progress of the Clean Architecture V2 https://github.com/ivanpaulovich/clean-architecture-manga/tree/v2

Regards,
Ivan
